---
apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: Kustomize Deploy
description: Deploy to Kubernetes cluster using a Kustomize config
inputs:
  kustomization-base-dir:
    description: Path to the base kustomize directory to apply / deploy
    required: true    
  kustomization-overlays-dir:
    description: Path to the overlays kustomize directory to apply / deploy
    required: true
  kustomize-annotation:
    description: >
     add/set/remove the annotations key-pairs for kustomizing.
     value example - 
        "{
            "remove": {
              "name1": "",
              "name2": ""
            },
            "add": {
              "name1": "value1",
              "name2": "value2"
            },
            "set": {
              "name1": "value1",
              "name2": "value2"
            }
        }"
   
    required: false
    default: "{}"
  kustomize-label:
    description: >
     add/set/remove the labels key-pairs for kustomizing.
     value example - 
          "{
              "remove": {
                "name1": "",
                "name2": ""
              },
              "add": {
                "name1": "value1",
                "name2": "value2"
              },
              "set": {
                "name1": "value1",
                "name2": "value2"
              }
          }"
    required: false
    default: "{}"
  kustomize-configmap-literal:
    description: >
     add the configmap literal keypairs for kustomizing.
     value example - 
          "{
              "name": "example-config",
              "add": {
                "name1": "value1",
                "name2": "value2"
              }
          }"
    required: false
    default: "{}"
  kustomize-configmap-file:
    description: >
     add the configmap file for kustomizing.
     value example -  
          "{
              "name":    "my-config",
              "add":     "config.properties"
          }"
    required: false
    default: "{}"
  kustomize-secret-file:
    description: >
     add the secret file for kustomizing.
     value example - 
        "{
            "name":    "my-secrets",
            "add":     "secret.properties",
        }"
    required: false
    default: "{}"
  kustomize-buildmetadata:
    description: >
     add/set/remove the build metadata for kustomizing.
     value example -  
        "{
            "add":  ["originAnnotations"],
            "set":   ["managedByLabel"] ,
            "remove": ["transformerAnnotations"]

        }"
        only allowed values are originAnnotations, managedByLabel, transformerAnnotations
    required: false
    default: "{}"
  kustomize-image: 
    description: >
     set the image for kustomizing.
     value example - 
        "{
            "name":    "nginx:1.7.9",
            "newName": "nginx",
            "newTag": "1.7.9-alpine"
        }"

    required: false
    default: "{}"
  kustomize-nameprefix:
    description: >
     set the nameprefix for kustomizing.
     value example - "dev-" 
    required: false
    default: ""
  kustomize-namesuffix:
    description: >
     set the namesuffix for kustomizing.
     value example - "V2" 
    required: false
    default: ""
  kustomize-namespace:
    description: >
     set the namespace for kustomizing.
     value example - "dev" 
    required: false
    default: ""
  kustomize-replicas:
    description: >
     set the replicas for kustomizing.
     value example - '["app:3","my-app:5"]'
    required: false
    default: "[]"

outputs:
  kustomize_output:
    value: ${{ steps.kustomize-deploy.outputs.kustomize_output_var }}
    description: kustomize  env variable output
    
runs:
  using: composite
  steps:
    - id: kustomize-deploy
      uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/kustomize-actions:main-6a13ece0cb320bdeb9d02e4c83a2905bc4e752b1
      shell: sh
      env: 
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{ step.internal.id }}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}

        CONFIG_JSON: '{"kustomization_base_dir":"${{ inputs.kustomization-base-dir }}","kustomization_overlays_dir":"${{ inputs.kustomization-overlays-dir }}","kustomize_annotation":${{ inputs.kustomize-annotation }},"kustomize_label":${{ inputs.kustomize-label }},"kustomize_configmap_literal":${{ inputs.kustomize-configmap-literal }},"kustomize_configmap_file":${{ inputs.kustomize-configmap-file }},"kustomize_secret_file":${{ inputs.kustomize-secret-file }},"kustomize_buildmetadata":${{ inputs.kustomize-buildmetadata }},"kustomize_image":${{ inputs.kustomize-image }},"kustomize_nameprefix":"${{ inputs.kustomize-nameprefix }}","kustomize_namesuffix":"${{ inputs.kustomize-namesuffix }}","kustomize_namespace":"${{ inputs.kustomize-namespace }}","kustomize_replicas":${{ inputs.kustomize-replicas }}}'
       
      run: |

        kustomize version
        set -x

        cd /app
        
    
         ./kustomize_app -i $CONFIG_JSON
         
