= CloudBees action: Deploy to a Kubernetes cluster using a Kustomize configuration

Use this action to customize Kubernetes configurations and resources with the  Kustomize, which uses overlays to change base YAML manifests without directly modifying them.

== Prerequisites

Make sure to initialize the connection using your AWS credentials, by adding the following to your YAML file:

[source,yaml]
----
      - name: Configure AWS credentials
        uses: cloudbees-io/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEU }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEU }}
          aws-region: ap-south-1
----

Refer to link:https://github.com/cloudbees-io/configure-aws-credentials[CloudBees action: Configure AWS credentials] for more information.

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `kustomization-base-dir`
| String
| Yes
| Path to the Kustomize base directory.

| `kustomization-overlays-dir`
| String
| No
| Path to the Kustomize overlay directory.

| `kustomize-annotation`
| JSON
| No
| add/set/remove the annotations for kustomizing.
[source,yaml]
----
    value example - 

    '{"add":{"nam1":"val1","nam2":"val2"},"set":{"nam1":"val1","nam2":"val2"},"remove":{"nam1":"val1","nam2":"val2"}}'
----


| `kustomize-label`
| JSON
| No
| add/set/remove the labels for kustomizing.
[source,yaml]
----
    value example - 

    '{"add":{"nam1":"val1","nam2":"val2"},"set":{"nam1":"val1","nam2":"val2"},"remove":{"nam1":"val1","nam2":"val2"}}'
----


| `kustomize-configmap-literal`
| JSON
| No
| add the configmap literal for kustomizing.
[source,yaml]
----
    value example - 

    '{"name":"example-config","add":{"nam1":"val1","nam2":"val2"}}'
----


| `kustomize-configmap-file`
| JSON
| No
| add the configmap file for kustomizing.
[source,yaml]
---- 
    value example - 

    '{"name":"my-config","add":"config.properties"}'
----

| `kustomize-secret-file`
| JSON
| No
| add the secret file for kustomizing.
[source,yaml]
----
    value example - 

    '{"name":"my-secret","add":"secrets.properties"}'
----

| `kustomize-buildmetadata`
| JSON
| No
| add/set/remove the build metadata for kustomizing.
  only allowed values are originAnnotations, managedByLabel, transformerAnnotations
[source,yaml]
---- 
    value example - 

    '{"add":["originAnnotations"],"set":["managedByLabel"],"remove":["transformerAnnotations"]}'      
----

| `kustomize-image`
| JSON
| No
| Set the image for kustomizing.
[source,yaml]
----
    value example - 

    '{"name":"nginx:1.7.9","newName":"nginx","newTag":"1.7.9-alpine"}'
----

| `kustomize-nameprefix`
| String
| No
| Set the nameprefix for kustomizing.
  value example - 
    
  "dev-" 

| `kustomize-namesuffix`
| String
| No
| Set the namesuffix for kustomizing.
    value example - 
     
    "V2" 

| `kustomize-namespace`
| String
| No
| Set the namespace for kustomizing.
    value example - 
     
    "dev" 

| `kustomize-replicas`
| JSON
| No
| Set the replicas for kustomizing.
[source,yaml]
----
     value example - 

      '["app:3","my-app:5"]'
----

|===

== Usage example

In your YAML file, add:

[source,yaml]
----
      - id: k8s-kustomize-deploy
        name: k8s-kustomize-deploy.
        uses: cloudbees-io/kustomize-deploy@v1
        with:
          kustomization-base-dir: ${{ cloudbees.workspace }}/testdata/base
          kustomization-overlays-dir: ${{ cloudbees.workspace }}/testdata/overlays/dev
          kustomize-annotation: '{"add":{"nam1":"val1","nam2":"val2"},"set":{"nam1":"val1","nam2":"val2"},"remove":{"nam1":"val1","nam2":"val2"}}'
          kustomize-label: '{"add":{"nam1":"val1","nam2":"val2"},"set":{"nam1":"val1","nam2":"val2"},"remove":{"nam1":"val1","nam2":"val2"}}'
          kustomize-configmap-literal: '{"name":"example-config","add":{"nam1":"val1","nam2":"val2"},"remove":{"nam1":"val1","nam2":"val2"}}'
          kustomize-configmap-file: '{"name":"my-config","add":"config.properties","remove":"config.properties"}'
          kustomize-secret-file: '{"name":"my-secret","namespace":"dev","add":"secrets.properties","set":"secrets.properties","remove":"secrets.properties"}'
          kustomize-buildmetadata: '{"add":["originAnnotations"],"set":["managedByLabel"],"remove":["transformerAnnotations"]}'
          kustomize-image: '{"name":"nginx:1.7.9","newName":"nginx","newTag":"1.7.9-alpine"}'
          kustomize-replicas: '["hello:5"]'
          kustomize-nameprefix: 'dev-'
          kustomize-namesuffix: '-v2'
          kustomize-namespace: 'dev'

----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform-actions/latest/[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-saas-platform/latest/[the CloudBees platform].
